# Generated by Django 4.2.17 on 2025-01-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('c_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('meter_type', models.CharField(choices=[('type1', '1'), ('type2', '2')], max_length=10)),
            ],
        ),
    ]
