# Generated by Django 4.2.17 on 2025-01-10 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='meter_type',
            field=models.CharField(choices=[('1', 'type1'), ('2', 'type2')], max_length=10),
        ),
        migrations.CreateModel(
            name='MonthlyMeterReadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('usage', models.FloatField()),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumer.user')),
            ],
            options={
                'unique_together': {('meter', 'month')},
            },
        ),
    ]
