# Generated by Django 4.2.17 on 2025-01-10 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0002_alter_user_meter_type_monthlymeterreadings'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyMeterReadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('usage', models.FloatField()),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumer.user')),
            ],
            options={
                'unique_together': {('meter', 'week')},
            },
        ),
        migrations.CreateModel(
            name='DailyMeterReadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField()),
                ('usage', models.FloatField()),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumer.user')),
            ],
            options={
                'unique_together': {('meter', 'hour')},
            },
        ),
    ]
